export const Resources = [
  ['bg', 'res/bg.jpg'],
  ['bullet', 'res/bullet.png'],
  ['enemy', 'res/enemy.png'],
  ['enemy', 'res/enemy.png'],
  ['hero', 'res/hero.png'],
  ['explosion1', 'res/explosion1.png'],
  ['begin','res/begin.png'],
  ['explosion1','res/explosion1.png'],
  ['explosion2','res/explosion2.png'],
  ['explosion3','res/explosion3.png'],
  ['explosion4','res/explosion4.png'],
  ['explosion5','res/explosion5.png'],
  ['explosion6','res/explosion6.png'],
  ['explosion7','res/explosion7.png'],
  ['explosion8','res/explosion8.png'],
  ['explosion9','res/explosion9.png'],
  ['explosion10','res/explosion10.png'],
  ['explosion11','res/explosion11.png'],
  ['explosion12','res/explosion12.png'],
  ['Common','res/Common.png'],
];